// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ruhauhfyfufchclixsiv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ1aGF1aGZ5ZnVmY2hjbGl4c2l2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMDgyNTAsImV4cCI6MjA2NDU4NDI1MH0.zQuJOitpDIqhUJjLmULlU6MHUBrTEq7H8GVKRT6hx_4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);